### ISSUE TITLE
Exception treatment

### ISSUE THREAD

**Issue by FFFF-duck** [yovanoc/Cookie#101]
I'm having a problem right after sign in the dofus account, it return this error:
System.IO.FileNotFoundException occour:
  HResult=0x80070002
  Message= Impossible to locate the archive: 'C:\Users\*\AppData\Local\Ankama\Dofus\app\data\i18n\i18n_fr.d2i'.
  Source=mscorlib
Actually, when I try to lauch the game without the updater I get the same error message at the game log screen

**Comment by yovanoc** [comment]
Oh okay, it's because we have only implemented french .. here : https://github.com/yovanoc/Cookie/blob/d23e157d02a696d64750807f4143e5c429270f2c/Cookie/MainForm.cs#L71 Change the "fr" by "en" :) and recompile the bot :)

**Comment by Apokah** [comment]
This is due to the fact that your dofus is not in French and the bot is looking for a french I18n file.
You can go here [https://github.com/yovanoc/Cookie/blob/de77235aa4d807f0c67dd8dd7dbd325e8ffa6609/Cookie/MainForm.cs#L71](url) and change the 'fr' to your language ^^

**Comment by FFFF-duck** [comment]
Oh sorry, and thx guys
